main_path:
  Home: "E:/01_Programming/Py/MasterThesis_CUDA/"
  Work: "C:/Users/Team Vaculin/PycharmProjects/MasterThesis_CUDA/"

YOLO:
  yolo8_m  : "yolo_models/yolov8m.pt"
  yolo8_l  : "yolo_models/yolov8l.pt"
  yolo8_seg: "yolo_models/yolov8seg.pt"

test_data:
  normal: "test_dataset/single_file/NT-70-40.mp4"
  crash: "test_dataset/single_file/50-40.mp4"
  near_miss: "test_dataset/single_file/40-28.mp4"
  dump_target: "E:/01_Programming/Py/MasterThesis_CUDA/test_dataset/dump_file/"

test_folder:
  test_sc1: "dataset/test_sc1/"
  test_sc2: "dataset/test_sc2/"
  test_sc3: "dataset/test_sc3/"
  test_sc4: "dataset/test_sc4/"
  test_sc5: "dataset/test_sc5/"

test_result:
  test_sc1: "dataset/result_sc1/"
  test_sc2: "dataset/result_sc2/"
  test_sc3: "dataset/result_sc3/"
  test_sc4: "dataset/result_sc4/"
  test_sc5: "dataset/result_sc5/"

yoflow_target:
  scenario1: "dataset/scenario1/"
  scenario2: "dataset/scenario2/"
  scenario3: "dataset/scenario3/"
  scenario4: "dataset/scenario4/"
  scenario5: "dataset/scenario5/"

yoflow_source_ssd:
  scenario1: "D:/BeamNG_dataset/Crash_8SC1/"

yoflow_source_home:
  scenario1: "under construction"